@echo off
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""AnimationAttributionEnabled"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""AnimationAttributionHashingEnabled"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""OverlayMinFPS"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""BufferCount"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""MaxBufferCount"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""AnimationsShiftKey"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""BackdropBlurCachingThrottleMs"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""ChildWindowDpiIsolation"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""ColorizationColor"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""ColorPrevalence"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""ConfigureInput"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableAdvancedDirectFlip"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableDeviceBitmaps"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableDeviceBitmapsForMultiAdapter"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableDrawListCaching"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableHologramCompositor"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableLockingMemory"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableProjectedShadows"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisableProjectedShadowsRendering"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""DisallowNonDrawListRendering"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""CompositionPolicy"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""Composition"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""MaxOutstandingFrames"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""FlipQueuePolicy"" /t REG_DWORD /d 0x00000004 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm"" /v ""IdleTimeout"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1