@echo off
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SeTokenSingletonAttributesConfig"" /t REG_DWORD /d 0x00000003 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""obcaseinsensitive"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MitigationOptions"" /t REG_BINARY /d 00000000000000000000000000000000000000000000000000000000000000000000000000000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MitigationAuditOptions"" /t REG_BINARY /d 000000000000000000000000000000000000000000000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""EAFModules"" /t REG_SZ /d """" /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""GlobalTimerResolutionRequests"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisableExceptionChainValidation"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SerializeTimerExpiration"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisableIFEOCaching"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogProfileOffset"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ForceForegroundBoostDecay"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DPCTimeout"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcSoftTimeout"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcCumulativeSoftTimeout"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogPeriod"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""VerifierDpcScalingFactor"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ThreadDpcEnable"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MinimumDpcRate"" /t REG_DWORD /d 0x99999999 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MaximumKernelWorkerThreads"" /t REG_DWORD /d 0x00002000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcRequestRate"" /t REG_DWORD /d 0x99999999 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcTimeLimit"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcTimeCount"" /t REG_DWORD /d 0x0000000a /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""IdleHalt"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ClockOwner"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PendingTickFlags"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MaximumDpcQueueDepth"" /t REG_DWORD /d 0x000003e8 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogProfileCumulativeDpcThreshold"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogProfileSingleDpcThreshold"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcLastCount"" /t REG_DWORD /d 0x000003e8 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcRoutineActive"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""QuantumEnd"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""InterruptLastCount"" /t REG_DWORD /d 0xffffffff /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""InterruptRate"" /t REG_DWORD /d 0x99999999 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ReadyThreadCount"" /t REG_DWORD /d 0x000000ff /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""KeSpinLockOrdering"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PriorityState"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DistributeTimers"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisableDynamicTick"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""TimerInterruptDelay"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MinimumIncrement"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MaximumIncrement"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PowerOffFrozenProcessors"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisableLightWeightSuspend"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcQueueDepth"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""AdjustDpcThreshold"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""IdealDpcRate"" /t REG_DWORD /d 0x99999999 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""InterruptSteeringFlags"" /t REG_DWORD /d 0x00000003 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SchedulerMaximumLatency"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DebugPollInterval"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""HyperStartDisabled"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SeLpacEnableWatsonReporting"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SeLpacEnableWatsonThrottling"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""AdminlessEnableWatsonReporting"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""AdminlessEnableWatsonThrottling"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""CyclesPerClockQuantum"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ForceDpcDmaCoalesce"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisablePrefetcher"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""LockPagesInMemory"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""KdDisable"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ThreadPriorityBoost"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PerfBootPerformance"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PerfBoostPolicy"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""CpuThrottle"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""SchedulerAssistThreadFlagOverride"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogProfileBufferSizeBytes"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DpcWatchdogProfileCumulativeDpcThresholdMs"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""PassiveWatchdogTimeout"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""DisableTsx"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""MaximumSharedReadyQueueSize"" /t REG_DWORD /d 0x000000ff /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""ClockRate"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""TimerResolution"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""TSCDeadline"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""UsePlatformClock"" /t REG_DWORD /d 0x00000000 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""Clock Rate"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""QuantumLength"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""QuantumSize"" /t REG_DWORD /d 0x00000001 /f >nul 2>&1
reg add ""HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"" /v ""InterruptRequestRate"" /t REG_DWORD /d 0x99999999 /f >nul 2>&1